dist: xenial
env:
  - DOCKER_REPO=puzlcloud

language: generic

addons:
  apt:
    packages:
    - jq
    - curl

services:
  - docker

before_script:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

script:
  - VERSION=$(jq -r .version ./package.json)
  - docker build -t ${DOCKER_REPO}/${TRAVIS_REPO_SLUG/*\/}:${VERSION}-${TRAVIS_BRANCH} .
  - docker push ${DOCKER_REPO}/${TRAVIS_REPO_SLUG/*\/}:${VERSION}-${TRAVIS_BRANCH}
  - curl -s -o /dev/null -w "%{http_code}" -X POST -F token=${TOKEN} -F ref=${TRAVIS_BRANCH} ${URL}
