sudo: required
language: generic

services:
  - docker

install:
  - curl -Lo skaffold https://storage.googleapis.com/skaffold/releases/latest/skaffold-linux-amd64
  - chmod +x skaffold
  - sudo mv skaffold /usr/local/bin

before_script:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

# if commit is tagged, then tag docker image with the tag & push image (otherwise tag with commit id & no push)
script:
  - |
    if [ "${TRAVIS_TAG}" = "" ]; then
      skaffold build --profile travis-ci
    else
      skaffold build --profile travis-release
    fi